### ISSUE TITLE
AWS::ApiGateway::BasePathMapping - Base path already exists

### ISSUE THREAD

**Issue by RNavaneethKumar** [aws/aws-extensions-for-dotnet-cli#102]
Hi,

I have a template file as below

```
Resources:
    Api:
        Type: AWS::Serverless::Api
        Properties:
            Name: DemoApi
            StageName: stage
    BasePathMapping:
        Type: AWS::ApiGateway::BasePathMapping
        Properties:
            BasePath: user
            DomainName: xyz.com
            RestApiId: !Ref Api
            Stage: !Ref Api.Stage
    Method1:
        Type: AWS::Serverless::Function
        Properties:
```

I am using dotnet lambda tools for deployment. When the template is deployed for the first time, it creates the API and creates the base path mappings as expected. However when I deploy the template on subsequent deployments, I get an error stating that the base path already exists. Following is the error 

> Base path already exists for this domain name (Service: AmazonApiGateway; Status Code: 409; Error Code: ConflictException; Request ID: 79b05492-4cd1-4575-aa20-f5fa34e186f9)

I expected the mappings would be deleted and recreated. Is there a way to solve this other than deleting all the mappings before every deployment?
