### ISSUE TITLE
Unable to set/update description of Lambda version when using AutoPublishAlias

### ISSUE THREAD

**Issue by SSkupien** [aws/aws-extensions-for-dotnet-cli#106]
Hi, I am new to AWS so please be aware that I can be naming things wrongly. 
I have CloudFormation script for Lambda that is triggered by events from SQS:
```
Resources:

  SomeLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: SomeName
      CodeUri:
        Bucket: !Ref Bucket
        Key: !Ref Path
      Handler: !Ref HandlerKey
      Runtime: dotnetcore2.1
      MemorySize: 512
      Role: !GetAtt SomeFunctionExecutionRole.Arn
      AutoPublishAlias: DEV
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SomeQueue.Arn
            BatchSize: 1
```
I don't have problem with this script. When deploying with it after changes in code it creates new version of Lambda and set DEV alias properly.
Unfortunately, I'm not satisfied with naming versions as only decimals (1, 2, 3, etc.) by AWS. I would like to connect these decimal versions with my versioning of the Lambda code. 

For eg. : 
AWS version     | My version number
1 | 0.1.0.0
2 | 0.1.0.1
3 | 0.1.0.3
... | ...

I came up with idea to set a Description of version on AWS as my version number(or name of .zip file with code that is used in a specific version) so it will be visible and easily readable.

My problem is that I can't set a version description when using AutoPublishAlias.
Is there a way to do it somehow? Without using additional commands and scripts. It is required to have all of that in one script.
