### ISSUE TITLE
Renaming parameters with Lambda tool

### ISSUE THREAD

**Issue by kvasnyj** [aws/aws-extensions-for-dotnet-cli#17]
Hello,

I tried to deploy a new version of a stack with renamed parameters, however, `Amazon Lambda Tools v.2.1.4` is expecting the old named parameters as well.

Command:
`dotnet lambda deploy-serverless --package /home/jenkins/workspace/jenkins.template --config-file /home/jenkins/workspace/aws-lambda-tools-stage.json --template-parameters Environment=stage`

Exception:
`Error creating CloudFormation change set: Parameters: [FunctionNameMetadata, FunctionNameValidate, HandlerNameMetadata, HandlerNameValidate] do not exist in the template`

CloudFormation script:
```
AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  Environment:
    Type: String
  FunctionName:
    Type: String
    Default: albx-analyzer-api-lambda
  HandlerName:
    Type: String
    Default: Albelli.AlbxAnalyzer.Api::Albelli.AlbxAnalyzer.Api.LambdaEntryPoint::FunctionHandlerAsync
```

How can I rename or delete cloud formation parameters without deleting the stack?
