### ISSUE TITLE
How to use 'dotnet ecs deploy-service' with CodePipeline, Fargate, and CloudFormation?

### ISSUE THREAD

**Issue by ThomasJaeger** [aws/aws-extensions-for-dotnet-cli#44]
How do I use the `dotnet ecs deploy-service` CLI command during a CodeBuild phase in a CodePipeline that is managed with CloudFormation?

I could probably figure out the command line options but I do not see any options for CloudFormation like the `Lambda` extension for `aws-extensions-for-dotnet-cli` where there is a `package-ci` command available.

Do you have any examples available?

**Comment by normj** [comment]
If you are coming to re:Invent you can come to my talk where I talk about this 😄 

The basic idea is in your codebuild stage you are just pushing the image to ECR and then outputting a JSON file that identifies the container in the task definition to the repository URI. Here is my buildspec.yml file I'm using in my upcoming talk.
```yaml
version: 0.2

env:
    parameter-store:
        DOCKER_TAG: "/CloudMosaic/prod/FrontendTag"
        DOCKER_REPO: "/CloudMosaic/prod/FrontendRepository"
phases:
  install:
    commands:
      - dotnet tool install -g Amazon.ECS.Tools
  build:
    commands:
      - cd ./Code/CloudMosaic/UI/CloudMosaic.Frontend
      - dotnet ecs push-image --tag $DOCKER_TAG
  post_build:
    commands:
      - printf '[{"name":"CloudMosaicFrontend","imageUri":"%s"}]' $DOCKER_REPO > imagedefinitions.json
artifacts:
  files:
    - ./Code/CloudMosaic/UI/CloudMosaic.Frontend/imagedefinitions.json
  discard-paths: yes
```

Then in the deploy stage of your pipeline use the ECS provider to update the service. Here is the snippet from my CloudFormation template that configures ECS in the pipeline. If you aren't using CloudFormation hopefully this helps translate to how ever you are setting up your pipeline.

```json
{
	"Name" : "Deploy-Frontend",
	"ActionTypeId" : {
		"Category" : "Deploy",
		"Provider" : "ECS",
		"Owner" : "AWS",
		"Version" : "1"
	},
	"InputArtifacts" : [
		{
			"Name" : "CloudMosaicFrontendBundle"
		}
	],
	"Configuration" : {
		"ClusterName" : { "Ref" : "FrontendCluster" },
		"ServiceName":  "Frontend",
		"FileName":  "imagedefinitions.json"
	},
	"RunOrder" : 3
}
```
