### ISSUE TITLE
Referencing a layer parameter inside AWS::Serverless::Function

### ISSUE THREAD

**Issue by RNavaneethKumar** [aws/aws-extensions-for-dotnet-cli#99]
I have a sam template which has multiple functions and all of these function refer a set of layers. When I set the layer arn directly, the package-ci command runs as expected by inspecting the layers. However, when I create a parameter with a default value and try to reference the parameter, the package-ci command throws the exception "Error parsing layer version arn into layer name and version number".

Below is a sample code
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
    LayerA:
        Type: String
        Default: arn:aws:lambda:us-east-1:xxxxx:layer:layerA:1
    LayerB:
        Type: String
        Default: arn:aws:lambda:us-east-1:xxxxx:layer:layerB:1

Resources:
    InsertResource:
        Type: AWS::Serverless::Function
        Properties:
            Handler: Resource::Resource.Functions::InsertResource
            Runtime: dotnetcore2.1
            CodeUri: ''
            MemorySize: 512
            Timeout: 30
            Role: null
            Policies:
            - AWSLambdaBasicExecutionRole
            Layers: 
            - !Ref LayerA
            - !Ref LayerB
            Events:
                PutResource:
                    Type: Api
                    Properties:
                        Path: "/resource"
                        Method: POST
    UpdateResource:
        Type: AWS::Serverless::Function
        Properties:
            Handler: Resource::Resource.Functions::UpdateResource
            Runtime: dotnetcore2.1
            CodeUri: ''
            MemorySize: 512
            Timeout: 30
            Role: null
            Policies:
            - AWSLambdaBasicExecutionRole
            Layers:
            - !Ref LayerA
            - !Ref LayerB
            Events:
                PutResource:
                    Type: Api
                    Properties:
                        Path: "/resource"
                        Method: PUT
```

Is there any way to solve this problem?
